# Generated by Django 3.2 on 2021-05-03 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('katalog', '0002_zakaznik'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vypujcka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rent_start', models.DateTimeField()),
                ('rent_end', models.DateTimeField()),
                ('price', models.IntegerField()),
            ],
        ),
    ]
